---
title: "Ingalls Standards Repository"
author: "RLionheart"
date: "6/3/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!--This document was created by knitting the README.Rmd file. Please edit that instead.-->

This repository contains all the relevant information the Ingalls Lab Standards. This includes the "original" standards list from pre-June 2020 (titled "Ingalls_Lab_Standards_old.csv") in the data_raw/ directory, and the latest standards list (titled "Ingalls_Lab_Standards.csv").

If you are looking to simply use the new Ingalls Standards list, download Ingalls_Lab_Standards.csv and use accordingly. If you would like to view a previous version of the standards, or see how changes were made, the **Structural_Changes.Rmd** markdown file manages the log history of changes to the original csv.


#### Change Log
4/8/20: Internal standards updated to reflect consistent naming scheme.  
4/20/20: Abbreviated compounds switched to full-length KEGG names.  
4/20/20: Adjusted compounds with incorrect capitalization.  
4/22/20: Added or removed symbols as required by KEGG names.  
4/23/20: Update last compounds not falling into the above groups.
4/23/20: Complete renaming of compounds, including those that didn't change from the original names.
4/28/20: Adjust vitamins to descriptive names.
4/29/20: Adjust abbreviations for consistency.
5/8/20: FINAL NAMES DECIDED FOR PRIMARY ID.
5/28/20: Bug fixes in final names.
5/28/20: First suggestions for Figure Name column.
6/3/20: Final Figure Names decided.
7/30/20: ChEBI names scraped from website and added in new column.
8/3/20: IUPAC, InCHI, and SMILES columns added to standards.
8/10/20: Classyfire classifications added for those compounds that have them.
10/14/20: First version of SQL-safe names introduced. 
10/22/20: Remove all trailing numbers from SQL-safe names. This is the column to be used for CMAP.


### Overview
In June of 2020, significant changes were made to the original Ingalls Standards sheet. For an itemized list of changes, see the below descriptions. Changes can also be viewed on the git log of this project, available at https://github.com/IngallsLabUW/Ingalls_Standards/commits/master.

Starting June of 2021, this repository will be tidied and reorganized. 
Changing all column names and stuff at the end so this markdown remains as backwards compatible as possible.
Keep the IUPAC/INCHI/SMILES stuff like title and molecular fomula? Check that.
prefer to have the manual entry of dates for latest downloads?
ALSO DROPPED CHEBI_OLD but kept it in the pre2020 version just in case.

ingalls_lab_standards is now updated with all structural changes.
shall we keep the empirical formulas, do we want to use the ones from pubchem? Currently have both, can drop one.
------

#### Conventions made in Summer 2020 Revamp

*Capitalization*  
* All "Acid"s changed to "acid", as per KEGG conventions. Example: 3-Sulfopyruvic Acid --> 3-Sulfopyruvic acid   
* First appearance of compound in complete name capitalized. Example: 7-dehydrocholesterol --> 7-Dehydrocholesterol, thiamine pyrophosphate --> Thiamine pyrophosphate  
* "B-compoundName" changed to beta-CompoundName. Example: B-ionine --> beta_Ionine  
* Second part of compound name lowercase. Example: Glutathione Disulfide --> Glutathione disulfide  

*Abbreviations*  
For compound names in figures, the column Compound_Name.figure provides an abbreviated verison of the compound name whenever possible.
* When possible, change compound names to acronyms. Example: S-Adenosylhomocysteine --> SAH
* Drop prefixes for compounds. Example: L-Cystathionine --> Cystathionine
* Drop unnecessary commas and apostrophes. Example: Guanosine monophosphate, 15N5 --> GMP 15N5

*Symbols, Database Ingestions*  
To facilitate compatibility with ingestion into other databases, SQL parsing, etc, the column Compound_Name.SQL removes any non-ASCII characters from the Compound_Name column. This column also incorporates the Compound_Name.figure shortened name, as those names often have already dropped special characters. 
* Example: Diacylglycerol 18:1-18:1 --> DAG 18s1_18s1

*Other specific changes*  
* All B12s --> Methylcobalamin, Hydroxocobalamin, etc.  
* All Vitamins changed to their descriptive name: Vitamine B1 --> Thiamine, Vitamin B2 --> Riboflavin, etc.  
* Remove Fraction1 and Fraction2 columns. Fix NADH and Riboflavin-5-phosphate ionization forms and z charges (SHA 51d3d3c).

*External database ingestion*
* ChEBI names added
* IUPAC, InCHL, SMILES names added
* Known Classyfire compound designation added


#### TODO Changes
* Set up system to keep note of changes to official KEGG compound names whether or not those changes are enacted.  
* Add stereoisomer orientation column.  
* List of all commonly used names for a compound (eg Glutamic acid == Glutamate).  
